/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetAlliancesAllianceIdOk (
  /* the full name of the alliance */
  allianceName: String,
  /* date_founded string */
  dateFounded: DateTime,
  /* the executor corporation ID, if this alliance is not closed */
  executorCorp: Option[Integer],
  /* the short name of the alliance */
  ticker: String
)

