/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetAlliancesAllianceIdIconsOk (
  /* px128x128 string */
  px128x128: Option[String],
  /* px64x64 string */
  px64x64: Option[String]
)

