/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCharactersCharacterIdClonesOk (
  homeLocation: Option[GetCharactersCharacterIdClonesHomeLocation],
  /* jump_clones array */
  jumpClones: List[GetCharactersCharacterIdClonesJumpClone],
  /* last_jump_date string */
  lastJumpDate: Option[DateTime]
)

