/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCharactersCharacterIdPlanets200Ok (
  /* last_update string */
  lastUpdate: DateTime,
  /* num_pins integer */
  numPins: Integer,
  /* owner_id integer */
  ownerId: Integer,
  /* planet_id integer */
  planetId: Integer,
  /* planet_type string */
  planetType: String,
  /* solar_system_id integer */
  solarSystemId: Integer,
  /* upgrade_level integer */
  upgradeLevel: Integer
)

