/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCharactersCharacterIdWalletJournal200Ok (
  /* Transaction amount. Positive when value transferred to the first party. Negative otherwise */
  amount: Option[Float],
  /* Wallet balance after transaction occurred */
  balance: Option[Float],
  /* Date and time of transaction */
  date: DateTime,
  extraInfo: Option[GetCharactersCharacterIdWalletJournalExtraInfo],
  /* first_party_id integer */
  firstPartyId: Option[Integer],
  /* first_party_type string */
  firstPartyType: Option[String],
  /* reason string */
  reason: Option[String],
  /* Unique journal reference ID */
  refId: Long,
  /* Transaction type, different type of transaction will populate different fields in `extra_info` */
  refType: String,
  /* second_party_id integer */
  secondPartyId: Option[Integer],
  /* second_party_type string */
  secondPartyType: Option[String],
  /* Tax amount received for tax related transactions */
  tax: Option[Float],
  /* the corporation ID receiving any tax paid */
  taxRecieverId: Option[Integer]
)

