/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetCharactersCharacterIdContacts200Ok (
  /* contact_id integer */
  contactId: Integer,
  /* contact_type string */
  contactType: String,
  /* Whether this contact is in the blocked list. Note a missing value denotes unknown, not true or false */
  isBlocked: Option[Boolean],
  /* Whether this contact is being watched */
  isWatched: Option[Boolean],
  /* Custom label of the contact */
  labelId: Option[Long],
  /* Standing of the contact */
  standing: Float
)

