/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails (
  /* in seconds */
  cycleTime: Option[Integer],
  /* head_radius number */
  headRadius: Option[Float],
  /* heads array */
  heads: List[GetCharactersCharacterIdPlanetsPlanetIdHead],
  /* product_type_id integer */
  productTypeId: Option[Integer],
  /* qty_per_cycle integer */
  qtyPerCycle: Option[Integer]
)

