/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetCharactersCharacterIdAssets200Ok (
  /* is_singleton boolean */
  isSingleton: Boolean,
  /* item_id integer */
  itemId: Long,
  /* location_flag string */
  locationFlag: String,
  /* location_id integer */
  locationId: Long,
  /* location_type string */
  locationType: String,
  /* quantity integer */
  quantity: Option[Integer],
  /* type_id integer */
  typeId: Integer
)

