/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetCharactersCharacterIdWalletJournalExtraInfo (
  /* alliance_id integer */
  allianceId: Option[Integer],
  /* character_id integer */
  characterId: Option[Integer],
  /* contract_id integer */
  contractId: Option[Integer],
  /* corporation_id integer */
  corporationId: Option[Integer],
  /* destroyed_ship_type_id integer */
  destroyedShipTypeId: Option[Integer],
  /* job_id integer */
  jobId: Option[Integer],
  /* location_id integer */
  locationId: Option[Long],
  /* npc_id integer */
  npcId: Option[Integer],
  /* npc_name string */
  npcName: Option[String],
  /* planet_id integer */
  planetId: Option[Integer],
  /* system_id integer */
  systemId: Option[Integer],
  /* transaction_id integer */
  transactionId: Option[Long]
)

