/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCorporationsCorporationIdOk (
  /* id of alliance that corporation is a member of, if any */
  allianceId: Option[Integer],
  /* ceo_id integer */
  ceoId: Integer,
  /* corporation_description string */
  corporationDescription: String,
  /* the full name of the corporation */
  corporationName: String,
  /* creation_date string */
  creationDate: Option[DateTime],
  /* creator_id integer */
  creatorId: Integer,
  /* faction string */
  faction: Option[String],
  /* member_count integer */
  memberCount: Integer,
  /* tax_rate number */
  taxRate: Float,
  /* the short name of the corporation */
  ticker: String,
  /* url string */
  url: String
)

