/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCharactersCharacterIdContracts200Ok (
  /* Who will accept the contract. If assignee_id is same as acceptorID then character ID else corporation ID (The contract accepted by the corporation) */
  acceptorId: Integer,
  /* ID to whom the contract is assigned, can be corporation or character ID */
  assigneeId: Integer,
  /* To whom the contract is available */
  availability: String,
  /* Buyout price (for Auctions only) */
  buyout: Option[Float],
  /* Collateral price (for Couriers only) */
  collateral: Option[Float],
  /* contract_id integer */
  contractId: Integer,
  /* Date of confirmation of contract */
  dateAccepted: Option[DateTime],
  /* Date of completed of contract */
  dateCompleted: Option[DateTime],
  /* Expiration date of the contract */
  dateExpired: DateTime,
  /* Сreation date of the contract */
  dateIssued: DateTime,
  /* Number of days to perform the contract */
  daysToComplete: Option[Integer],
  /* End location ID (for Couriers contract) */
  endLocationId: Option[Long],
  /* true if the contract was issued on behalf of the issuer's corporation */
  forCorporation: Boolean,
  /* Character's corporation ID for the issuer */
  issuerCorporationId: Integer,
  /* Character ID for the issuer */
  issuerId: Integer,
  /* Price of contract (for ItemsExchange and Auctions) */
  price: Option[Float],
  /* Remuneration for contract (for Couriers only) */
  reward: Option[Float],
  /* Start location ID (for Couriers contract) */
  startLocationId: Option[Long],
  /* Status of the the contract */
  status: String,
  /* Title of the contract */
  title: Option[String],
  /* Type of the contract */
  _type: String,
  /* Volume of items in the contract */
  volume: Option[Float]
)

