/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCharactersCharacterIdOk (
  /* The character's alliance ID */
  allianceId: Option[Integer],
  /* ancestry_id integer */
  ancestryId: Option[Integer],
  /* Creation date of the character */
  birthday: DateTime,
  /* bloodline_id integer */
  bloodlineId: Integer,
  /* The character's corporation ID */
  corporationId: Integer,
  /* description string */
  description: Option[String],
  /* gender string */
  gender: String,
  /* name string */
  name: String,
  /* race_id integer */
  raceId: Integer,
  /* security_status number */
  securityStatus: Option[Float]
)

