/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetCharactersCharacterIdBookmarksFolders200Ok (
  /* folder_id integer */
  folderId: Option[Integer],
  /* name string */
  name: Option[String],
  /* owner_id integer */
  ownerId: Option[Integer]
)

