/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetCharactersCharacterIdContractsContractIdItems200Ok (
  /* true if the contract issuer has submitted this item with the contract, false if the isser is asking for this item in the contract. */
  isIncluded: Boolean,
  /* is_singleton boolean */
  isSingleton: Boolean,
  /* Number of items in the stack */
  quantity: Integer,
  /* -1 indicates that the item is a singleton (non-stackable). If the item happens to be a Blueprint, -1 is an Original and -2 is a Blueprint Copy */
  rawQuantity: Option[Integer],
  /* Unique ID for the item */
  recordId: Long,
  /* Type ID for item */
  typeId: Integer
)

