/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCharactersCharacterIdMail200Ok (
  /* From whom the mail was sent */
  from: Option[Integer],
  /* is_read boolean */
  isRead: Option[Boolean],
  /* labels array */
  labels: Option[List[Long]],
  /* mail_id integer */
  mailId: Option[Long],
  /* Recipients of the mail */
  recipients: Option[List[GetCharactersCharacterIdMailRecipient]],
  /* Mail subject */
  subject: Option[String],
  /* When the mail was sent */
  timestamp: Option[DateTime]
)

