/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCharactersCharacterIdCalendarEventIdOk (
  /* date string */
  date: DateTime,
  /* Length in minutes */
  duration: Integer,
  /* event_id integer */
  eventId: Integer,
  /* importance integer */
  importance: Integer,
  /* owner_id integer */
  ownerId: Integer,
  /* owner_name string */
  ownerName: String,
  /* owner_type string */
  ownerType: String,
  /* response string */
  response: String,
  /* text string */
  text: String,
  /* title string */
  title: String
)

