/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCorporationsCorporationIdMembertracking200Ok (
  /* base_id integer */
  baseId: Option[Integer],
  /* character_id integer */
  characterId: Integer,
  /* location_id integer */
  locationId: Option[Long],
  /* logoff_date string */
  logoffDate: Option[DateTime],
  /* logon_date string */
  logonDate: Option[DateTime],
  /* ship_type_id integer */
  shipTypeId: Option[Integer],
  /* start_date string */
  startDate: Option[DateTime]
)

