/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCharactersCharacterIdAgentsResearch200Ok (
  /* agent_id integer */
  agentId: Integer,
  /* points_per_day number */
  pointsPerDay: Float,
  /* remainder_points number */
  remainderPoints: Float,
  /* skill_type_id integer */
  skillTypeId: Integer,
  /* started_at string */
  startedAt: DateTime
)

