/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetCharactersCharacterIdSkillsSkill (
  /* current_skill_level integer */
  currentSkillLevel: Option[Integer],
  /* skill_id integer */
  skillId: Option[Integer],
  /* skillpoints_in_skill integer */
  skillpointsInSkill: Option[Long]
)

