/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetCharactersCharacterIdMailLabelsLabel (
  /* color string */
  color: Option[String],
  /* label_id integer */
  labelId: Option[Integer],
  /* name string */
  name: Option[String],
  /* unread_count integer */
  unreadCount: Option[Integer]
)

