/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCharactersCharacterIdWalletTransactions200Ok (
  /* client_id integer */
  clientId: Integer,
  /* Date and time of transaction */
  date: DateTime,
  /* is_buy boolean */
  isBuy: Boolean,
  /* is_personal boolean */
  isPersonal: Boolean,
  /* journal_ref_id integer */
  journalRefId: Long,
  /* location_id integer */
  locationId: Long,
  /* quantity integer */
  quantity: Integer,
  /* Unique transaction ID */
  transactionId: Long,
  /* type_id integer */
  typeId: Integer,
  /* Amount paid per unit */
  unitPrice: Integer
)

