/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCharactersCharacterIdMailMailIdOk (
  /* Mail's body */
  body: Option[String],
  /* From whom the mail was sent */
  from: Option[Integer],
  /* Labels attached to the mail */
  labels: Option[List[Long]],
  /* Whether the mail is flagged as read */
  read: Option[Boolean],
  /* Recipients of the mail */
  recipients: Option[List[GetCharactersCharacterIdMailMailIdRecipient]],
  /* Mail subject */
  subject: Option[String],
  /* When the mail was sent */
  timestamp: Option[DateTime]
)

