/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCharactersCharacterIdFatigueOk (
  /* Character's jump fatigue expiry */
  jumpFatigueExpireDate: Option[DateTime],
  /* Character's last jump activation */
  lastJumpDate: Option[DateTime],
  /* Character's last jump update */
  lastUpdateDate: Option[DateTime]
)

