/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCharactersCharacterIdMedals200Ok (
  /* corporation_id integer */
  corporationId: Integer,
  /* date string */
  date: DateTime,
  /* description string */
  description: String,
  /* graphics array */
  graphics: List[GetCharactersCharacterIdMedalsGraphic],
  /* issuer_id integer */
  issuerId: Integer,
  /* medal_id integer */
  medalId: Integer,
  /* reason string */
  reason: String,
  /* status string */
  status: String,
  /* title string */
  title: String
)

