/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetCharactersCharacterIdOrders200Ok (
  /* Wallet division for the buyer or seller of this order. Always 1000 for characters. Currently 1000 through 1006 for corporations */
  accountId: Integer,
  /* Numer of days for which order is valid (starting from the issued date). An order expires at time issued + duration */
  duration: Integer,
  /* For buy orders, the amount of ISK in escrow */
  escrow: Float,
  /* True for a bid (buy) order. False for an offer (sell) order */
  isBuyOrder: Boolean,
  /* is_corp boolean */
  isCorp: Boolean,
  /* Date and time when this order was issued */
  issued: DateTime,
  /* ID of the location where order was placed */
  locationId: Long,
  /* For bids (buy orders), the minimum quantity that will be accepted in a matching offer (sell order) */
  minVolume: Integer,
  /* Unique order ID */
  orderId: Long,
  /* Cost per unit for this order */
  price: Float,
  /* Valid order range, numbers are ranges in jumps */
  range: String,
  /* ID of the region where order was placed */
  regionId: Integer,
  /* Current order state */
  state: String,
  /* The type ID of the item transacted in this order */
  typeId: Integer,
  /* Quantity of items still required or offered */
  volumeRemain: Integer,
  /* Quantity of items required or offered at time order was placed */
  volumeTotal: Integer
)

