/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetDogmaEffectsEffectIdModifier (
  /* domain string */
  domain: Option[String],
  /* effect_id integer */
  effectId: Option[Integer],
  /* func string */
  func: String,
  /* modified_attribute_id integer */
  modifiedAttributeId: Option[Integer],
  /* modifying_attribute_id integer */
  modifyingAttributeId: Option[Integer],
  /* operator integer */
  operator: Option[Integer]
)

