/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetFwStats200Ok (
  /* faction_id integer */
  factionId: Integer,
  kills: Option[GetFwStatsKills],
  /* How many pilots fight for the given faction */
  pilots: Integer,
  /* The number of solar systems controlled by the given faction */
  systemsControlled: Integer,
  victoryPoints: Option[GetFwStatsVictoryPoints]
)

