/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetFleetsFleetIdMembers200Ok (
  /* character_id integer */
  characterId: Integer,
  /* join_time string */
  joinTime: DateTime,
  /* Member’s role in fleet */
  role: String,
  /* Localized role names */
  roleName: String,
  /* ship_type_id integer */
  shipTypeId: Integer,
  /* Solar system the member is located in */
  solarSystemId: Integer,
  /* ID of the squad the member is in. If not applicable, will be set to -1 */
  squadId: Long,
  /* Station in which the member is docked in, if applicable */
  stationId: Option[Long],
  /* Whether the member take fleet warps */
  takesFleetWarp: Boolean,
  /* ID of the wing the member is in. If not applicable, will be set to -1 */
  wingId: Long
)

