/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetFleetsFleetIdOk (
  /* Is free-move enabled */
  isFreeMove: Boolean,
  /* Does the fleet have an active fleet advertisement */
  isRegistered: Boolean,
  /* Is EVE Voice enabled */
  isVoiceEnabled: Boolean,
  /* Fleet MOTD in CCP flavoured HTML */
  motd: String
)

