/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetFwStatsVictoryPoints (
  /* Last week's victory points gained */
  lastWeek: Integer,
  /* Total victory points gained since faction warfare began */
  total: Integer,
  /* Yesterday's victory points gained */
  yesterday: Integer
)

