/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetFwLeaderboardsCharactersKills (
  /* Top 100 ranking of pilots active in faction warfare by total kills. A pilot is considered \"active\" if they have participated in faction warfare in the past 14 days. */
  activeTotal: List[GetFwLeaderboardsCharactersActiveTotal],
  /* Top 100 ranking of pilots by kills in the past week */
  lastWeek: List[GetFwLeaderboardsCharactersLastWeek],
  /* Top 100 ranking of pilots by kills in the past day */
  yesterday: List[GetFwLeaderboardsCharactersYesterday]
)

