/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetIncursions200Ok (
  /* The constellation id in which this incursion takes place */
  constellationId: Integer,
  /* The attacking faction's id */
  factionId: Integer,
  /* Whether the final encounter has boss or not */
  hasBoss: Boolean,
  /* A list of infested solar system ids that are a part of this incursion */
  infestedSolarSystems: List[Integer],
  /* Influence of this incursion as a float from 0 to 1 */
  influence: Float,
  /* Staging solar system for this incursion */
  stagingSolarSystemId: Integer,
  /* The state of this incursion */
  state: String,
  /* The type of this incursion */
  _type: String
)

