/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetIndustryFacilities200Ok (
  /* ID of the facility */
  facilityId: Long,
  /* Owner of the facility */
  ownerId: Integer,
  /* Region ID where the facility is */
  regionId: Integer,
  /* Solar system ID where the facility is */
  solarSystemId: Integer,
  /* Tax imposed by the facility */
  tax: Option[Float],
  /* Type ID of the facility */
  typeId: Integer
)

