/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetKillmailsKillmailIdKillmailHashItem1 (
  /* Flag for the location of the item  */
  flag: Integer,
  /* item_type_id integer */
  itemTypeId: Integer,
  /* items array */
  items: Option[List[GetKillmailsKillmailIdKillmailHashItem]],
  /* How many of the item were destroyed if any  */
  quantityDestroyed: Option[Long],
  /* How many of the item were dropped if any  */
  quantityDropped: Option[Long],
  /* singleton integer */
  singleton: Integer
)

