/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetKillmailsKillmailIdKillmailHashVictim (
  /* alliance_id integer */
  allianceId: Option[Integer],
  /* character_id integer */
  characterId: Option[Integer],
  /* corporation_id integer */
  corporationId: Option[Integer],
  /* How much total damage was taken by the victim  */
  damageTaken: Integer,
  /* faction_id integer */
  factionId: Option[Integer],
  /* items array */
  items: Option[List[GetKillmailsKillmailIdKillmailHashItem1]],
  position: Option[GetKillmailsKillmailIdKillmailHashPosition],
  /* The ship that the victim was piloting and was destroyed  */
  shipTypeId: Integer
)

