/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetLoyaltyStoresCorporationIdOffers200Ok (
  /* isk_cost number */
  iskCost: Number,
  /* lp_cost integer */
  lpCost: Integer,
  /* offer_id integer */
  offerId: Integer,
  /* quantity integer */
  quantity: Integer,
  /* required_items array */
  requiredItems: List[GetLoyaltyStoresCorporationIdOffersRequiredItem],
  /* type_id integer */
  typeId: Integer
)

