/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model
import java.lang.Double

case class GetMarketsPrices200Ok (
  /* adjusted_price number */
  adjustedPrice: Option[Double],
  /* average_price number */
  averagePrice: Option[Double],
  /* type_id integer */
  typeId: Integer
)

