/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetMarketsRegionIdOrders200Ok (
  /* duration integer */
  duration: Integer,
  /* is_buy_order boolean */
  isBuyOrder: Boolean,
  /* issued string */
  issued: DateTime,
  /* location_id integer */
  locationId: Long,
  /* min_volume integer */
  minVolume: Integer,
  /* order_id integer */
  orderId: Long,
  /* price number */
  price: Float,
  /* range string */
  range: String,
  /* type_id integer */
  typeId: Integer,
  /* volume_remain integer */
  volumeRemain: Integer,
  /* volume_total integer */
  volumeTotal: Integer
)

