/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetMarketsGroupsMarketGroupIdOk (
  /* description string */
  description: String,
  /* market_group_id Int */
  marketGroupId: Int,
  /* name string */
  name: String,
  /* parent_group_id Int */
  parentGroupId: Option[Int],
  /* types array */
  types: List[Int]
)

