/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import java.util.Date
import java.lang._


case class GetMarketsRegionIdHistory200Ok (
                                            /* average number */
                                            average: Float,
                                            /* The date of this historical statistic entry */
                                            date: Date,
                                            /* highest number */
                                            highest: Float,
                                            /* lowest number */
                                            lowest: Float,
                                            /* Total number of orders happened that day */
                                            orderCount: Long,
                                            /* Total */
                                            volume: Long
)

