/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetSovereigntyCampaigns200Ok (
  /* Score for all attacking parties, only present in Defense Events.  */
  attackersScore: Option[Float],
  /* Unique ID for this campaign. */
  campaignId: Integer,
  /* The constellation in which the campaign will take place.  */
  constellationId: Integer,
  /* Defending alliance, only present in Defense Events  */
  defenderId: Option[Integer],
  /* Score for the defending alliance, only present in Defense Events.  */
  defenderScore: Option[Float],
  /* Type of event this campaign is for. tcu_defense, ihub_defense and station_defense are referred to as \"Defense Events\", station_freeport as \"Freeport Events\".  */
  eventType: String,
  /* Alliance participating and their respective scores, only present in Freeport Events.  */
  participants: Option[List[GetSovereigntyCampaignsParticipant]],
  /* The solar system the structure is located in.  */
  solarSystemId: Integer,
  /* Time the event is scheduled to start.  */
  startTime: DateTime,
  /* The structure item ID that is related to this campaign.  */
  structureId: Long
)

