/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetUniverseGroupsGroupIdOk (
  /* category_id integer */
  categoryId: Integer,
  /* group_id integer */
  groupId: Integer,
  /* name string */
  name: String,
  /* published boolean */
  published: Boolean,
  /* types array */
  types: List[Integer]
)

