/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import java.lang._

case class GetUniverseTypesTypeIdOk (
  /* capacity number */
  capacity: Option[Float],
  /* description string */
  description: String,
  /* dogma_attributes array */
  dogmaAttributes: Option[List[GetUniverseTypesTypeIdDogmaAttribute]],
  /* dogma_effects array */
  dogmaEffects: Option[List[GetUniverseTypesTypeIdDogmaEffect]],
  /* graphic_id Int */
  graphicId: Option[Int],
  /* group_id Int */
  groupId: Int,
  /* icon_id Int */
  iconId: Option[Int],
  /* mass number */
  mass: Option[Float],
  /* name string */
  name: String,
  /* portion_size Int */
  portionSize: Option[Int],
  /* published boolean */
  published: Boolean,
  /* radius number */
  radius: Option[Float],
  /* type_id Int */
  typeId: Int,
  /* volume number */
  volume: Option[Float]
)

