/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetUniverseGraphicsGraphicIdOk (
  /* collision_file string */
  collisionFile: Option[String],
  /* graphic_file string */
  graphicFile: Option[String],
  /* graphic_id integer */
  graphicId: Integer,
  /* icon_folder string */
  iconFolder: Option[String],
  /* sof_dna string */
  sofDna: Option[String],
  /* sof_fation_name string */
  sofFationName: Option[String],
  /* sof_hull_name string */
  sofHullName: Option[String],
  /* sof_race_name string */
  sofRaceName: Option[String]
)

