/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetUniverseBloodlines200Ok (
  /* bloodline_id integer */
  bloodlineId: Integer,
  /* charisma integer */
  charisma: Integer,
  /* corporation_id integer */
  corporationId: Integer,
  /* description string */
  description: String,
  /* intelligence integer */
  intelligence: Integer,
  /* memory integer */
  memory: Integer,
  /* name string */
  name: String,
  /* perception integer */
  perception: Integer,
  /* race_id integer */
  raceId: Integer,
  /* ship_type_id integer */
  shipTypeId: Integer,
  /* willpower integer */
  willpower: Integer
)

