/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetUniverseFactions200Ok (
  /* corporation_id integer */
  corporationId: Integer,
  /* description string */
  description: String,
  /* faction_id integer */
  factionId: Integer,
  /* is_unique boolean */
  isUnique: Boolean,
  /* militia_corporation_id integer */
  militiaCorporationId: Option[Integer],
  /* name string */
  name: String,
  /* size_factor number */
  sizeFactor: Float,
  /* solar_system_id integer */
  solarSystemId: Integer,
  /* station_count integer */
  stationCount: Integer,
  /* station_system_count integer */
  stationSystemCount: Integer
)

