/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetUniverseRaces200Ok (
  /* The alliance generally associated with this race */
  allianceId: Integer,
  /* description string */
  description: String,
  /* name string */
  name: String,
  /* race_id integer */
  raceId: Integer
)

