/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetUniverseStargatesStargateIdOk (
  destination: Option[GetUniverseStargatesStargateIdDestination],
  /* name string */
  name: String,
  position: Option[GetUniverseStargatesStargateIdPosition],
  /* stargate_id integer */
  stargateId: Integer,
  /* The solar system this stargate is in */
  systemId: Integer,
  /* type_id integer */
  typeId: Integer
)

