/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetUniverseSystemKills200Ok (
  /* Number of NPC ships killed in this system */
  npcKills: Integer,
  /* Number of pods killed in this system */
  podKills: Integer,
  /* Number of player ships killed in this system */
  shipKills: Integer,
  /* system_id integer */
  systemId: Integer
)

