/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import org.joda.time.DateTime

case class GetWarsWarIdOk (
  aggressor: Option[GetWarsWarIdAggressor],
  /* allied corporations or alliances, each object contains either corporation_id or alliance_id */
  allies: Option[List[GetWarsWarIdAlly]],
  /* Time that the war was declared */
  declared: DateTime,
  defender: Option[GetWarsWarIdDefender],
  /* Time the war ended and shooting was no longer allowed */
  finished: Option[DateTime],
  /* ID of the specified war */
  id: Integer,
  /* Was the war declared mutual by both parties */
  mutual: Boolean,
  /* Is the war currently open for allies or not */
  openForAllies: Boolean,
  /* Time the war was retracted but both sides could still shoot each other */
  retracted: Option[DateTime],
  /* Time when the war started and both sides could shoot each other */
  started: Option[DateTime]
)

