/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetWarsWarIdAggressor (
  /* Alliance ID if and only if the aggressor is an alliance */
  allianceId: Option[Integer],
  /* Corporation ID if and only if the aggressor is a corporation */
  corporationId: Option[Integer],
  /* ISK value of ships the aggressor has destroyed */
  iskDestroyed: Float,
  /* The number of ships the aggressor has killed */
  shipsKilled: Integer
)

