/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class GetWarsWarIdAlly (
  /* Alliance ID if and only if this ally is an alliance */
  allianceId: Option[Integer],
  /* Corporation ID if and only if this ally is a corporation */
  corporationId: Option[Integer]
)

