/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class PostCharactersAffiliation200Ok (
  /* The character's alliance ID, if their corporation is in an alliance */
  allianceId: Option[Integer],
  /* The character's ID */
  characterId: Integer,
  /* The character's corporation ID */
  corporationId: Integer,
  /* The character's faction ID, if their corporation is in a faction */
  factionId: Option[Integer]
)

