/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class PostUiOpenwindowNewmailNewMail (
  /* body string */
  body: String,
  /* recipients array */
  recipients: List[Integer],
  /* subject string */
  subject: String,
  /* to_corp_or_alliance_id integer */
  toCorpOrAllianceId: Option[Integer],
  /* Corporations, alliances and mailing lists are all types of mailing groups. You may only send to one mailing group, at a time, so you may fill out either this field or the to_corp_or_alliance_ids field */
  toMailingListId: Option[Integer]
)

