/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class PutCharactersCharacterIdMailMailIdContents (
  /* Labels to assign to the mail. Pre-existing labels are unassigned. */
  labels: Option[List[Long]],
  /* Whether the mail is flagged as read */
  read: Option[Boolean]
)

