/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

case class PutCorporationsCorporationIdStructuresStructureIdNewSchedule (
  /* Day of the week, zero-indexed to Monday */
  day: Integer,
  /* Hour of the day evetime, zero-indexed to midnight */
  hour: Integer
)

